/**
 * Solartis Create Customer API for ILT
 * To create customer for Leisure Travel from Solartis Rate API.Umbrella insurance is extra liability insurance.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModelMessageDetailMessageList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorModelMessageDetailMessageList'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisCreateCustomerApiForIlt) {
      root.SolartisCreateCustomerApiForIlt = {};
    }
    root.SolartisCreateCustomerApiForIlt.ErrorModelMessageDetail = factory(root.SolartisCreateCustomerApiForIlt.ApiClient, root.SolartisCreateCustomerApiForIlt.ErrorModelMessageDetailMessageList);
  }
}(this, function(ApiClient, ErrorModelMessageDetailMessageList) {
  'use strict';




  /**
   * The ErrorModelMessageDetail model module.
   * @module model/ErrorModelMessageDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ErrorModelMessageDetail</code>.
   * @alias module:model/ErrorModelMessageDetail
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ErrorModelMessageDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorModelMessageDetail} obj Optional instance to populate.
   * @return {module:model/ErrorModelMessageDetail} The populated <code>ErrorModelMessageDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('MessageCode')) {
        obj['MessageCode'] = ApiClient.convertToType(data['MessageCode'], 'String');
      }
      if (data.hasOwnProperty('MessageType')) {
        obj['MessageType'] = ApiClient.convertToType(data['MessageType'], 'String');
      }
      if (data.hasOwnProperty('UserMessage')) {
        obj['UserMessage'] = ApiClient.convertToType(data['UserMessage'], 'String');
      }
      if (data.hasOwnProperty('MessageLevel')) {
        obj['MessageLevel'] = ApiClient.convertToType(data['MessageLevel'], 'String');
      }
      if (data.hasOwnProperty('MessageSeverity')) {
        obj['MessageSeverity'] = ApiClient.convertToType(data['MessageSeverity'], 'String');
      }
      if (data.hasOwnProperty('MessageList')) {
        obj['MessageList'] = ErrorModelMessageDetailMessageList.constructFromObject(data['MessageList']);
      }
    }
    return obj;
  }

  /**
   * @member {String} MessageCode
   */
  exports.prototype['MessageCode'] = undefined;
  /**
   * @member {String} MessageType
   */
  exports.prototype['MessageType'] = undefined;
  /**
   * @member {String} UserMessage
   */
  exports.prototype['UserMessage'] = undefined;
  /**
   * @member {String} MessageLevel
   */
  exports.prototype['MessageLevel'] = undefined;
  /**
   * @member {String} MessageSeverity
   */
  exports.prototype['MessageSeverity'] = undefined;
  /**
   * @member {module:model/ErrorModelMessageDetailMessageList} MessageList
   */
  exports.prototype['MessageList'] = undefined;



  return exports;
}));


