/**
 * Solartis Create Customer API for ILT
 * To create customer for Leisure Travel from Solartis Rate API.Umbrella insurance is extra liability insurance.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisCreateCustomerApiForIlt) {
      root.SolartisCreateCustomerApiForIlt = {};
    }
    root.SolartisCreateCustomerApiForIlt.RequestCustomerInformationTravelerList = factory(root.SolartisCreateCustomerApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestCustomerInformationTravelerList model module.
   * @module model/RequestCustomerInformationTravelerList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestCustomerInformationTravelerList</code>.
   * @alias module:model/RequestCustomerInformationTravelerList
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>RequestCustomerInformationTravelerList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestCustomerInformationTravelerList} obj Optional instance to populate.
   * @return {module:model/RequestCustomerInformationTravelerList} The populated <code>RequestCustomerInformationTravelerList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TravelerDOB')) {
        obj['TravelerDOB'] = ApiClient.convertToType(data['TravelerDOB'], 'String');
      }
      if (data.hasOwnProperty('TravelCost')) {
        obj['TravelCost'] = ApiClient.convertToType(data['TravelCost'], 'String');
      }
      if (data.hasOwnProperty('FirstName')) {
        obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
      }
      if (data.hasOwnProperty('LastName')) {
        obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
      }
      if (data.hasOwnProperty('AddressLine1')) {
        obj['AddressLine1'] = ApiClient.convertToType(data['AddressLine1'], 'String');
      }
      if (data.hasOwnProperty('City')) {
        obj['City'] = ApiClient.convertToType(data['City'], 'String');
      }
      if (data.hasOwnProperty('State')) {
        obj['State'] = ApiClient.convertToType(data['State'], 'String');
      }
      if (data.hasOwnProperty('StateCode')) {
        obj['StateCode'] = ApiClient.convertToType(data['StateCode'], 'String');
      }
      if (data.hasOwnProperty('Country')) {
        obj['Country'] = ApiClient.convertToType(data['Country'], 'String');
      }
      if (data.hasOwnProperty('Zipcode')) {
        obj['Zipcode'] = ApiClient.convertToType(data['Zipcode'], 'String');
      }
      if (data.hasOwnProperty('Phone')) {
        obj['Phone'] = ApiClient.convertToType(data['Phone'], 'String');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('TravelerIndex')) {
        obj['TravelerIndex'] = ApiClient.convertToType(data['TravelerIndex'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} TravelerDOB
   * @default '02/14/1990'
   */
  exports.prototype['TravelerDOB'] = '02/14/1990';
  /**
   * @member {String} TravelCost
   * @default '2500'
   */
  exports.prototype['TravelCost'] = '2500';
  /**
   * @member {String} FirstName
   * @default 'John'
   */
  exports.prototype['FirstName'] = 'John';
  /**
   * @member {String} LastName
   * @default 'Doe'
   */
  exports.prototype['LastName'] = 'Doe';
  /**
   * @member {String} AddressLine1
   * @default '399 park avenue'
   */
  exports.prototype['AddressLine1'] = '399 park avenue';
  /**
   * @member {String} City
   * @default 'Atlanta'
   */
  exports.prototype['City'] = 'Atlanta';
  /**
   * @member {String} State
   * @default 'Georgia'
   */
  exports.prototype['State'] = 'Georgia';
  /**
   * @member {String} StateCode
   * @default 'GA'
   */
  exports.prototype['StateCode'] = 'GA';
  /**
   * @member {String} Country
   * @default 'United States'
   */
  exports.prototype['Country'] = 'United States';
  /**
   * @member {String} Zipcode
   * @default '30301'
   */
  exports.prototype['Zipcode'] = '30301';
  /**
   * @member {String} Phone
   * @default '4045555512'
   */
  exports.prototype['Phone'] = '4045555512';
  /**
   * @member {String} Email
   * @default 'test@solartis.net'
   */
  exports.prototype['Email'] = 'test@solartis.net';
  /**
   * @member {String} TravelerIndex
   * @default '1'
   */
  exports.prototype['TravelerIndex'] = '1';



  return exports;
}));


