/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisRateApiForIlt) {
      root.SolartisRateApiForIlt = {};
    }
    root.SolartisRateApiForIlt.RatingRequestQuoteInformationTravelerList = factory(root.SolartisRateApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RatingRequestQuoteInformationTravelerList model module.
   * @module model/RatingRequestQuoteInformationTravelerList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RatingRequestQuoteInformationTravelerList</code>.
   * @alias module:model/RatingRequestQuoteInformationTravelerList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RatingRequestQuoteInformationTravelerList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatingRequestQuoteInformationTravelerList} obj Optional instance to populate.
   * @return {module:model/RatingRequestQuoteInformationTravelerList} The populated <code>RatingRequestQuoteInformationTravelerList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TravelerDOB')) {
        obj['TravelerDOB'] = ApiClient.convertToType(data['TravelerDOB'], 'String');
      }
      if (data.hasOwnProperty('TravelCost')) {
        obj['TravelCost'] = ApiClient.convertToType(data['TravelCost'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} TravelerDOB
   * @default '02/14/1990'
   */
  exports.prototype['TravelerDOB'] = '02/14/1990';
  /**
   * @member {String} TravelCost
   * @default '2500'
   */
  exports.prototype['TravelCost'] = '2500';



  return exports;
}));


