/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisRateApiForIlt) {
      root.SolartisRateApiForIlt = {};
    }
    root.SolartisRateApiForIlt.RatingRequestServiceRequestDetail = factory(root.SolartisRateApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RatingRequestServiceRequestDetail model module.
   * @module model/RatingRequestServiceRequestDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RatingRequestServiceRequestDetail</code>.
   * @alias module:model/RatingRequestServiceRequestDetail
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>RatingRequestServiceRequestDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatingRequestServiceRequestDetail} obj Optional instance to populate.
   * @return {module:model/RatingRequestServiceRequestDetail} The populated <code>RatingRequestServiceRequestDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ServiceRequestVersion')) {
        obj['ServiceRequestVersion'] = ApiClient.convertToType(data['ServiceRequestVersion'], 'String');
      }
      if (data.hasOwnProperty('ServiceResponseVersion')) {
        obj['ServiceResponseVersion'] = ApiClient.convertToType(data['ServiceResponseVersion'], 'String');
      }
      if (data.hasOwnProperty('OwnerId')) {
        obj['OwnerId'] = ApiClient.convertToType(data['OwnerId'], 'String');
      }
      if (data.hasOwnProperty('ResponseType')) {
        obj['ResponseType'] = ApiClient.convertToType(data['ResponseType'], 'String');
      }
      if (data.hasOwnProperty('RegionCode')) {
        obj['RegionCode'] = ApiClient.convertToType(data['RegionCode'], 'String');
      }
      if (data.hasOwnProperty('Token')) {
        obj['Token'] = ApiClient.convertToType(data['Token'], 'String');
      }
      if (data.hasOwnProperty('UserName')) {
        obj['UserName'] = ApiClient.convertToType(data['UserName'], 'String');
      }
      if (data.hasOwnProperty('LanguageCode')) {
        obj['LanguageCode'] = ApiClient.convertToType(data['LanguageCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} ServiceRequestVersion
   * @default '1.0'
   */
  exports.prototype['ServiceRequestVersion'] = '1.0';
  /**
   * @member {String} ServiceResponseVersion
   * @default '1.0'
   */
  exports.prototype['ServiceResponseVersion'] = '1.0';
  /**
   * @member {String} OwnerId
   * @default '15'
   */
  exports.prototype['OwnerId'] = '15';
  /**
   * @member {module:model/RatingRequestServiceRequestDetail.ResponseTypeEnum} ResponseType
   * @default 'JSON'
   */
  exports.prototype['ResponseType'] = 'JSON';
  /**
   * @member {String} RegionCode
   * @default 'US'
   */
  exports.prototype['RegionCode'] = 'US';
  /**
   * @member {String} Token
   * @default 'iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0AZz+lxADORmgRpwMLooWQp506Ue4quZZNMZosssVnBIFbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD'
   */
  exports.prototype['Token'] = 'iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0AZz+lxADORmgRpwMLooWQp506Ue4quZZNMZosssVnBIFbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD';
  /**
   * @member {String} UserName
   * @default 'travelagent'
   */
  exports.prototype['UserName'] = 'travelagent';
  /**
   * @member {String} LanguageCode
   * @default 'en'
   */
  exports.prototype['LanguageCode'] = 'en';


  /**
   * Allowed values for the <code>ResponseType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ResponseTypeEnum = {
    /**
     * value: "JSON"
     * @const
     */
    "JSON": "JSON",
    /**
     * value: "XML"
     * @const
     */
    "XML": "XML"  };


  return exports;
}));


