/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RatingRequestQuoteInformationTravelerList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RatingRequestQuoteInformationTravelerList'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisRateApiForIlt) {
      root.SolartisRateApiForIlt = {};
    }
    root.SolartisRateApiForIlt.RatingRequestQuoteInformation = factory(root.SolartisRateApiForIlt.ApiClient, root.SolartisRateApiForIlt.RatingRequestQuoteInformationTravelerList);
  }
}(this, function(ApiClient, RatingRequestQuoteInformationTravelerList) {
  'use strict';




  /**
   * The RatingRequestQuoteInformation model module.
   * @module model/RatingRequestQuoteInformation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RatingRequestQuoteInformation</code>.
   * @alias module:model/RatingRequestQuoteInformation
   * @class
   */
  var exports = function() {
    var _this = this;























  };

  /**
   * Constructs a <code>RatingRequestQuoteInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatingRequestQuoteInformation} obj Optional instance to populate.
   * @return {module:model/RatingRequestQuoteInformation} The populated <code>RatingRequestQuoteInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ProductID')) {
        obj['ProductID'] = ApiClient.convertToType(data['ProductID'], 'String');
      }
      if (data.hasOwnProperty('ProductVerID')) {
        obj['ProductVerID'] = ApiClient.convertToType(data['ProductVerID'], 'String');
      }
      if (data.hasOwnProperty('ProductNumber')) {
        obj['ProductNumber'] = ApiClient.convertToType(data['ProductNumber'], 'String');
      }
      if (data.hasOwnProperty('ProductVerNumber')) {
        obj['ProductVerNumber'] = ApiClient.convertToType(data['ProductVerNumber'], 'String');
      }
      if (data.hasOwnProperty('ProducerCode')) {
        obj['ProducerCode'] = ApiClient.convertToType(data['ProducerCode'], 'String');
      }
      if (data.hasOwnProperty('OwnerId')) {
        obj['OwnerId'] = ApiClient.convertToType(data['OwnerId'], 'String');
      }
      if (data.hasOwnProperty('PlanName')) {
        obj['PlanName'] = ApiClient.convertToType(data['PlanName'], 'String');
      }
      if (data.hasOwnProperty('PlanCode')) {
        obj['PlanCode'] = ApiClient.convertToType(data['PlanCode'], 'String');
      }
      if (data.hasOwnProperty('DepartureDate')) {
        obj['DepartureDate'] = ApiClient.convertToType(data['DepartureDate'], 'String');
      }
      if (data.hasOwnProperty('ReturnDate')) {
        obj['ReturnDate'] = ApiClient.convertToType(data['ReturnDate'], 'String');
      }
      if (data.hasOwnProperty('DepositDate')) {
        obj['DepositDate'] = ApiClient.convertToType(data['DepositDate'], 'String');
      }
      if (data.hasOwnProperty('DestinationCountry')) {
        obj['DestinationCountry'] = ApiClient.convertToType(data['DestinationCountry'], 'String');
      }
      if (data.hasOwnProperty('PolicyEffectiveDate')) {
        obj['PolicyEffectiveDate'] = ApiClient.convertToType(data['PolicyEffectiveDate'], 'String');
      }
      if (data.hasOwnProperty('RentalStartDate')) {
        obj['RentalStartDate'] = ApiClient.convertToType(data['RentalStartDate'], 'String');
      }
      if (data.hasOwnProperty('RentalEndDate')) {
        obj['RentalEndDate'] = ApiClient.convertToType(data['RentalEndDate'], 'String');
      }
      if (data.hasOwnProperty('RentalLimit')) {
        obj['RentalLimit'] = ApiClient.convertToType(data['RentalLimit'], 'String');
      }
      if (data.hasOwnProperty('NumberOfRentalCars')) {
        obj['NumberOfRentalCars'] = ApiClient.convertToType(data['NumberOfRentalCars'], 'String');
      }
      if (data.hasOwnProperty('TripCancellationCoverage')) {
        obj['TripCancellationCoverage'] = ApiClient.convertToType(data['TripCancellationCoverage'], 'String');
      }
      if (data.hasOwnProperty('StateCode')) {
        obj['StateCode'] = ApiClient.convertToType(data['StateCode'], 'String');
      }
      if (data.hasOwnProperty('QuoteType')) {
        obj['QuoteType'] = ApiClient.convertToType(data['QuoteType'], 'String');
      }
      if (data.hasOwnProperty('EventName')) {
        obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
      }
      if (data.hasOwnProperty('TravelerList')) {
        obj['TravelerList'] = ApiClient.convertToType(data['TravelerList'], [RatingRequestQuoteInformationTravelerList]);
      }
    }
    return obj;
  }

  /**
   * @member {String} ProductID
   * @default '619'
   */
  exports.prototype['ProductID'] = '619';
  /**
   * @member {String} ProductVerID
   * @default '706'
   */
  exports.prototype['ProductVerID'] = '706';
  /**
   * @member {String} ProductNumber
   * @default 'ILT'
   */
  exports.prototype['ProductNumber'] = 'ILT';
  /**
   * @member {String} ProductVerNumber
   * @default '1.0'
   */
  exports.prototype['ProductVerNumber'] = '1.0';
  /**
   * @member {String} ProducerCode
   * @default '86201'
   */
  exports.prototype['ProducerCode'] = '86201';
  /**
   * @member {String} OwnerId
   * @default '15'
   */
  exports.prototype['OwnerId'] = '15';
  /**
   * @member {String} PlanName
   * @default 'Air Ticket Protector'
   */
  exports.prototype['PlanName'] = 'Air Ticket Protector';
  /**
   * @member {String} PlanCode
   * @default '1'
   */
  exports.prototype['PlanCode'] = '1';
  /**
   * @member {String} DepartureDate
   * @default '06/25/2017'
   */
  exports.prototype['DepartureDate'] = '06/25/2017';
  /**
   * @member {String} ReturnDate
   * @default '06/31/2017'
   */
  exports.prototype['ReturnDate'] = '06/31/2017';
  /**
   * @member {String} DepositDate
   * @default '06/03/2017'
   */
  exports.prototype['DepositDate'] = '06/03/2017';
  /**
   * @member {String} DestinationCountry
   * @default 'France'
   */
  exports.prototype['DestinationCountry'] = 'France';
  /**
   * @member {String} PolicyEffectiveDate
   * @default '06/25/2017'
   */
  exports.prototype['PolicyEffectiveDate'] = '06/25/2017';
  /**
   * @member {String} RentalStartDate
   * @default '06/25/2017'
   */
  exports.prototype['RentalStartDate'] = '06/25/2017';
  /**
   * @member {String} RentalEndDate
   * @default '06/31/2017'
   */
  exports.prototype['RentalEndDate'] = '06/31/2017';
  /**
   * @member {String} RentalLimit
   * @default '35000'
   */
  exports.prototype['RentalLimit'] = '35000';
  /**
   * @member {String} NumberOfRentalCars
   * @default '1'
   */
  exports.prototype['NumberOfRentalCars'] = '1';
  /**
   * @member {String} TripCancellationCoverage
   * @default 'With Trip Cancellation'
   */
  exports.prototype['TripCancellationCoverage'] = 'With Trip Cancellation';
  /**
   * @member {String} StateCode
   * @default 'GA'
   */
  exports.prototype['StateCode'] = 'GA';
  /**
   * @member {String} QuoteType
   * @default 'New Business'
   */
  exports.prototype['QuoteType'] = 'New Business';
  /**
   * @member {String} EventName
   * @default 'InvokeRatingV2'
   */
  exports.prototype['EventName'] = 'InvokeRatingV2';
  /**
   * @member {Array.<module:model/RatingRequestQuoteInformationTravelerList>} TravelerList
   */
  exports.prototype['TravelerList'] = undefined;



  return exports;
}));


