/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RatingRequestQuoteInformation', 'model/RatingRequestServiceRequestDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RatingRequestQuoteInformation'), require('./RatingRequestServiceRequestDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisRateApiForIlt) {
      root.SolartisRateApiForIlt = {};
    }
    root.SolartisRateApiForIlt.RatingRequest = factory(root.SolartisRateApiForIlt.ApiClient, root.SolartisRateApiForIlt.RatingRequestQuoteInformation, root.SolartisRateApiForIlt.RatingRequestServiceRequestDetail);
  }
}(this, function(ApiClient, RatingRequestQuoteInformation, RatingRequestServiceRequestDetail) {
  'use strict';




  /**
   * The RatingRequest model module.
   * @module model/RatingRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RatingRequest</code>.
   * @alias module:model/RatingRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RatingRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatingRequest} obj Optional instance to populate.
   * @return {module:model/RatingRequest} The populated <code>RatingRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ServiceRequestDetail')) {
        obj['ServiceRequestDetail'] = RatingRequestServiceRequestDetail.constructFromObject(data['ServiceRequestDetail']);
      }
      if (data.hasOwnProperty('QuoteInformation')) {
        obj['QuoteInformation'] = RatingRequestQuoteInformation.constructFromObject(data['QuoteInformation']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RatingRequestServiceRequestDetail} ServiceRequestDetail
   */
  exports.prototype['ServiceRequestDetail'] = undefined;
  /**
   * @member {module:model/RatingRequestQuoteInformation} QuoteInformation
   */
  exports.prototype['QuoteInformation'] = undefined;



  return exports;
}));


