/**
 * Solartis Rate API for ILT
 * To get rate for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModel', 'model/RatingRequest', 'model/RatingSuccessResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorModel'), require('../model/RatingRequest'), require('../model/RatingSuccessResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisRateApiForIlt) {
      root.SolartisRateApiForIlt = {};
    }
    root.SolartisRateApiForIlt.DefaultApi = factory(root.SolartisRateApiForIlt.ApiClient, root.SolartisRateApiForIlt.ErrorModel, root.SolartisRateApiForIlt.RatingRequest, root.SolartisRateApiForIlt.RatingSuccessResponse);
  }
}(this, function(ApiClient, ErrorModel, RatingRequest, RatingSuccessResponse) {
  'use strict';

  /**
   * Default service.
   * @module api/DefaultApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DefaultApi. 
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getRates operation.
     * @callback module:api/DefaultApi~getRatesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RatingSuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets Rate for Leisure Travel
     * @param {String} token Authentication Token
     * @param {String} contentType Content Type
     * @param {String} eventName EventName
     * @param {module:model/RatingRequest} ratingRequest For rating request
     * @param {module:api/DefaultApi~getRatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RatingSuccessResponse}
     */
    this.getRates = function(token, contentType, eventName, ratingRequest, callback) {
      var postBody = ratingRequest;

      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling getRates");
      }

      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling getRates");
      }

      // verify the required parameter 'eventName' is set
      if (eventName === undefined || eventName === null) {
        throw new Error("Missing the required parameter 'eventName' when calling getRates");
      }

      // verify the required parameter 'ratingRequest' is set
      if (ratingRequest === undefined || ratingRequest === null) {
        throw new Error("Missing the required parameter 'ratingRequest' when calling getRates");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Token': token,
        'Content-Type': contentType,
        'EventName': eventName
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = RatingSuccessResponse;

      return this.apiClient.callApi(
        '/FireEventV2', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
