/**
 * Solartis Policy Issuance API for ILT
 * To Policy Issuance for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisPolicyIssuanceApiForIlt) {
      root.SolartisPolicyIssuanceApiForIlt = {};
    }
    root.SolartisPolicyIssuanceApiForIlt.ErrorModelMessageDetailMessageList = factory(root.SolartisPolicyIssuanceApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ErrorModelMessageDetailMessageList model module.
   * @module model/ErrorModelMessageDetailMessageList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ErrorModelMessageDetailMessageList</code>.
   * @alias module:model/ErrorModelMessageDetailMessageList
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ErrorModelMessageDetailMessageList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorModelMessageDetailMessageList} obj Optional instance to populate.
   * @return {module:model/ErrorModelMessageDetailMessageList} The populated <code>ErrorModelMessageDetailMessageList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Message')) {
        obj['Message'] = ApiClient.convertToType(data['Message'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} Message
   */
  exports.prototype['Message'] = undefined;



  return exports;
}));


