/**
 * Solartis Policy Issuance API for ILT
 * To Policy Issuance for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisPolicyIssuanceApiForIlt) {
      root.SolartisPolicyIssuanceApiForIlt = {};
    }
    root.SolartisPolicyIssuanceApiForIlt.RequestPolicyInformation = factory(root.SolartisPolicyIssuanceApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestPolicyInformation model module.
   * @module model/RequestPolicyInformation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestPolicyInformation</code>.
   * @alias module:model/RequestPolicyInformation
   * @class
   */
  var exports = function() {
    var _this = this;


























  };

  /**
   * Constructs a <code>RequestPolicyInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestPolicyInformation} obj Optional instance to populate.
   * @return {module:model/RequestPolicyInformation} The populated <code>RequestPolicyInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ProductID')) {
        obj['ProductID'] = ApiClient.convertToType(data['ProductID'], 'String');
      }
      if (data.hasOwnProperty('ProductVerID')) {
        obj['ProductVerID'] = ApiClient.convertToType(data['ProductVerID'], 'String');
      }
      if (data.hasOwnProperty('ProductNumber')) {
        obj['ProductNumber'] = ApiClient.convertToType(data['ProductNumber'], 'String');
      }
      if (data.hasOwnProperty('ProductVerNumber')) {
        obj['ProductVerNumber'] = ApiClient.convertToType(data['ProductVerNumber'], 'String');
      }
      if (data.hasOwnProperty('ProducerCode')) {
        obj['ProducerCode'] = ApiClient.convertToType(data['ProducerCode'], 'String');
      }
      if (data.hasOwnProperty('OwnerId')) {
        obj['OwnerId'] = ApiClient.convertToType(data['OwnerId'], 'String');
      }
      if (data.hasOwnProperty('CustomerNumber')) {
        obj['CustomerNumber'] = ApiClient.convertToType(data['CustomerNumber'], 'String');
      }
      if (data.hasOwnProperty('RoleID')) {
        obj['RoleID'] = ApiClient.convertToType(data['RoleID'], 'String');
      }
      if (data.hasOwnProperty('RoleName')) {
        obj['RoleName'] = ApiClient.convertToType(data['RoleName'], 'String');
      }
      if (data.hasOwnProperty('RoleType')) {
        obj['RoleType'] = ApiClient.convertToType(data['RoleType'], 'String');
      }
      if (data.hasOwnProperty('EventName')) {
        obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
      }
      if (data.hasOwnProperty('CardNumber')) {
        obj['CardNumber'] = ApiClient.convertToType(data['CardNumber'], 'String');
      }
      if (data.hasOwnProperty('CVV')) {
        obj['CVV'] = ApiClient.convertToType(data['CVV'], 'String');
      }
      if (data.hasOwnProperty('ExpiryMonth')) {
        obj['ExpiryMonth'] = ApiClient.convertToType(data['ExpiryMonth'], 'String');
      }
      if (data.hasOwnProperty('ExpiryYear')) {
        obj['ExpiryYear'] = ApiClient.convertToType(data['ExpiryYear'], 'String');
      }
      if (data.hasOwnProperty('PayerName')) {
        obj['PayerName'] = ApiClient.convertToType(data['PayerName'], 'String');
      }
      if (data.hasOwnProperty('PayerAddress1')) {
        obj['PayerAddress1'] = ApiClient.convertToType(data['PayerAddress1'], 'String');
      }
      if (data.hasOwnProperty('PayerCity')) {
        obj['PayerCity'] = ApiClient.convertToType(data['PayerCity'], 'String');
      }
      if (data.hasOwnProperty('PayerState')) {
        obj['PayerState'] = ApiClient.convertToType(data['PayerState'], 'String');
      }
      if (data.hasOwnProperty('PayerCountry')) {
        obj['PayerCountry'] = ApiClient.convertToType(data['PayerCountry'], 'String');
      }
      if (data.hasOwnProperty('PayerZipcode')) {
        obj['PayerZipcode'] = ApiClient.convertToType(data['PayerZipcode'], 'String');
      }
      if (data.hasOwnProperty('PayerEmail')) {
        obj['PayerEmail'] = ApiClient.convertToType(data['PayerEmail'], 'String');
      }
      if (data.hasOwnProperty('PayerPhone')) {
        obj['PayerPhone'] = ApiClient.convertToType(data['PayerPhone'], 'String');
      }
      if (data.hasOwnProperty('PaymentMethod')) {
        obj['PaymentMethod'] = ApiClient.convertToType(data['PaymentMethod'], 'String');
      }
      if (data.hasOwnProperty('CardType')) {
        obj['CardType'] = ApiClient.convertToType(data['CardType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} ProductID
   * @default '619'
   */
  exports.prototype['ProductID'] = '619';
  /**
   * @member {String} ProductVerID
   * @default '706'
   */
  exports.prototype['ProductVerID'] = '706';
  /**
   * @member {String} ProductNumber
   * @default 'ILT'
   */
  exports.prototype['ProductNumber'] = 'ILT';
  /**
   * @member {String} ProductVerNumber
   * @default '1.0'
   */
  exports.prototype['ProductVerNumber'] = '1.0';
  /**
   * @member {String} ProducerCode
   * @default '86201'
   */
  exports.prototype['ProducerCode'] = '86201';
  /**
   * @member {String} OwnerId
   * @default '15'
   */
  exports.prototype['OwnerId'] = '15';
  /**
   * @member {String} CustomerNumber
   * @default 'SC1700006650KCP0'
   */
  exports.prototype['CustomerNumber'] = 'SC1700006650KCP0';
  /**
   * @member {String} RoleID
   * @default '5'
   */
  exports.prototype['RoleID'] = '5';
  /**
   * @member {String} RoleName
   * @default 'Agent'
   */
  exports.prototype['RoleName'] = 'Agent';
  /**
   * @member {String} RoleType
   * @default 'User'
   */
  exports.prototype['RoleType'] = 'User';
  /**
   * @member {String} EventName
   * @default 'Pay_Issue'
   */
  exports.prototype['EventName'] = 'Pay_Issue';
  /**
   * @member {String} CardNumber
   * @default '5555555555554444'
   */
  exports.prototype['CardNumber'] = '5555555555554444';
  /**
   * @member {String} CVV
   * @default '123'
   */
  exports.prototype['CVV'] = '123';
  /**
   * @member {String} ExpiryMonth
   * @default '11'
   */
  exports.prototype['ExpiryMonth'] = '11';
  /**
   * @member {String} ExpiryYear
   * @default '2018'
   */
  exports.prototype['ExpiryYear'] = '2018';
  /**
   * @member {String} PayerName
   * @default 'John Doe'
   */
  exports.prototype['PayerName'] = 'John Doe';
  /**
   * @member {String} PayerAddress1
   * @default '399 Park st'
   */
  exports.prototype['PayerAddress1'] = '399 Park st';
  /**
   * @member {String} PayerCity
   * @default 'Atlanta'
   */
  exports.prototype['PayerCity'] = 'Atlanta';
  /**
   * @member {String} PayerState
   * @default 'GA'
   */
  exports.prototype['PayerState'] = 'GA';
  /**
   * @member {String} PayerCountry
   * @default 'US'
   */
  exports.prototype['PayerCountry'] = 'US';
  /**
   * @member {String} PayerZipcode
   * @default '30301'
   */
  exports.prototype['PayerZipcode'] = '30301';
  /**
   * @member {String} PayerEmail
   * @default 'test@solartis.net'
   */
  exports.prototype['PayerEmail'] = 'test@solartis.net';
  /**
   * @member {String} PayerPhone
   * @default '4045555512'
   */
  exports.prototype['PayerPhone'] = '4045555512';
  /**
   * @member {String} PaymentMethod
   * @default 'Credit Card'
   */
  exports.prototype['PaymentMethod'] = 'Credit Card';
  /**
   * @member {String} CardType
   * @default 'MasterCard'
   */
  exports.prototype['CardType'] = 'MasterCard';



  return exports;
}));


