/**
 * Solartis Policy Issuance API for ILT
 * To Policy Issuance for Leisure Travel from Solartis Rate API.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SolartisPolicyIssuanceApiForIlt) {
      root.SolartisPolicyIssuanceApiForIlt = {};
    }
    root.SolartisPolicyIssuanceApiForIlt.SuccessResponse = factory(root.SolartisPolicyIssuanceApiForIlt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SuccessResponse model module.
   * @module model/SuccessResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SuccessResponse</code>.
   * @alias module:model/SuccessResponse
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SuccessResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuccessResponse} obj Optional instance to populate.
   * @return {module:model/SuccessResponse} The populated <code>SuccessResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messageDetail')) {
        obj['messageDetail'] = ApiClient.convertToType(data['messageDetail'], Object);
      }
      if (data.hasOwnProperty('ResponseStatus')) {
        obj['ResponseStatus'] = ApiClient.convertToType(data['ResponseStatus'], 'String');
      }
      if (data.hasOwnProperty('Policy')) {
        obj['Policy'] = ApiClient.convertToType(data['Policy'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Object} messageDetail
   */
  exports.prototype['messageDetail'] = undefined;
  /**
   * @member {String} ResponseStatus
   */
  exports.prototype['ResponseStatus'] = undefined;
  /**
   * @member {Object} Policy
   */
  exports.prototype['Policy'] = undefined;



  return exports;
}));


